# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnZ1IjGatOG2rlOzY_NWG0jLizpnL3is
"""

# Создание списка
students = ["Анна", "Борис", "Виктория"]
grades = [4, 5, 3, 4, 5]
mixed_list = [1, "текст", 3.14, True]

# Создание кортежа
coordinates = (55.7558, 37.6173)
colors = ("красный", "зеленый", "синий")
single_element = (42,)  # Запятая обязательна!

# Создание множества
unique_numbers = {1, 2, 3, 2, 1}  # {1, 2, 3}
empty_set = set()  # {} создаст словарь!

# Создание словаря
student = {
    "имя": "Мария",
    "возраст": 20,
    "курс": 2,
    "оценки": [4, 5, 4, 5]
}

# Исходные данные
text = """
Python является одним из самых популярных языков программирования.
Язык Python прост в изучении и эффективен в использовании.
Python используется в веб-разработке, анализе данных, искусственном интеллекте.
"""

def analyze_text(text):
    """
    Проанализировать текст и вернуть статистику:
    - общее количество слов
    - количество уникальных слов
    - список слов в верхнем регистре
    """
    # Разбить текст на слова (убрать знаки препинания и привести к нижнему регистру)
    words = text.lower().split()
    cleaned_words = [word.strip('.,!?;:()') for word in words]

    # TODO: Вычислить общее количество слов
    total_words = len(cleaned_words)

    # TODO: Найти уникальные слова с помощью множества
    unique_words = set(cleaned_words)

    # TODO: Создать список слов в верхнем регистре (длиннее 3 символов)
    uppercase_words = [word.upper() for word in cleaned_words if len(word) > 3]

    return {
        "total_words": total_words,
        "unique_words_count": len(unique_words),
        "unique_words": unique_words,
        "uppercase_words": uppercase_words
    }

# Проверка работы функции
result = analyze_text(text)
print(f"Общее количество слов: {result['total_words']}")
print(f"Уникальных слов: {result['unique_words_count']}")
print(f"Пример уникальных слов: {list(result['unique_words'])[:5]}")

def create_student_database():
    """
    Создать базу данных студентов и реализовать операции:
    - добавление студента
    - поиск по имени
    - расчет среднего балла
    - вывод студентов с оценкой выше заданной
    """
    students = {}

    def add_student(student_id, name, age, grades):
        """
        Добавить студента в базу данных
        grades должен быть списком оценок
        """
        # TODO: Реализовать добавление студента
        students[student_id] = {
            "имя": name,
            "возраст": age,
            "оценки": grades,
            "средний_балл": sum(grades) / len(grades) if grades else 0
        }

    def find_student(name):
        """Найти всех студентов с указанным именем"""
        # TODO: Реализовать поиск по имени
        found = []
        for student_id, info in students.items():
            if info["имя"].lower() == name.lower():
                found.append((student_id, info))
        return found

    def get_top_students(threshold=4.0):
        """Вернуть студентов со средним баллом выше threshold"""
        # TODO: Реализовать фильтрацию по среднему баллу
        top_students = {}
        for student_id, info in students.items():
            if info["средний_балл"] >= threshold:
                top_students[student_id] = info
        return top_students

    # Добавляем тестовых студентов
    add_student(1, "Анна Иванова", 20, [5, 4, 5, 5])
    add_student(2, "Петр Сидоров", 21, [3, 4, 4, 3])
    add_student(3, "Мария Козлова", 19, [5, 5, 5, 5])

    # TODO: Протестировать функции
    print("Все студенты:", students)
    print("Поиск 'Анна':", find_student("Анна"))
    print("Топ студенты:", get_top_students(4.5))

    return students

# Запуск базы данных
database = create_student_database()

def analyze_sales_data():
    """
    Проанализировать данные о продажах и вывести:
    - общую выручку по каждому товару
    - самый популярный товар
    - среднюю стоимость заказа
    """

    # Данные о продажах: список словарей
    sales = [
        {"product": "ноутбук", "price": 50000, "quantity": 2, "date": "2024-01-15"},
        {"product": "мышь", "price": 1500, "quantity": 5, "date": "2024-01-15"},
        {"product": "ноутбук", "price": 50000, "quantity": 1, "date": "2024-01-16"},
        {"product": "клавиатура", "price": 3000, "quantity": 3, "date": "2024-01-16"},
        {"product": "монитор", "price": 20000, "quantity": 2, "date": "2024-01-17"},
    ]

    def calculate_product_revenue(sales_data):
        """Рассчитать общую выручку по каждому товару"""
        revenue_by_product = {}
        for sale in sales_data:
            product = sale["product"]
            revenue = sale["price"] * sale["quantity"]

            if product in revenue_by_product:
                revenue_by_product[product] += revenue
            else:
                revenue_by_product[product] = revenue
        return revenue_by_product

    def find_most_popular_product(sales_data):
        """Найти товар с наибольшим количеством продаж"""
        quantity_by_product = {}
        for sale in sales_data:
            product = sale["product"]
            quantity = sale["quantity"]

            if product in quantity_by_product:
                quantity_by_product[product] += quantity
            else:
                quantity_by_product[product] = quantity

        # TODO: Найти товар с максимальным количеством
        if quantity_by_product:
            return max(quantity_by_product, key=quantity_by_product.get)
        return None

    def calculate_average_order_value(sales_data):
        """Рассчитать среднюю стоимость одного заказа"""
        total_revenue = 0
        total_orders = len(sales_data)

        for sale in sales_data:
            total_revenue += sale["price"] * sale["quantity"]

        return total_revenue / total_orders if total_orders > 0 else 0

    # Выполняем анализ
    product_revenue = calculate_product_revenue(sales)
    popular_product = find_most_popular_product(sales)
    avg_order = calculate_average_order_value(sales)

    print("Выручка по товарам:", product_revenue)
    print("Самый популярный товар:", popular_product)
    print("Средняя стоимость заказа:", f"{avg_order:.2f} руб.")

    return product_revenue

# Запуск анализа
analysis_results = analyze_sales_data()

